# Generated by Django 2.2.16 on 2023-08-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название поста')),
                ('text', models.TextField(max_length=2000, verbose_name='текс поста')),
            ],
        ),
    ]
