# Generated by Django 2.2.16 on 2023-08-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20230830_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_forum',
            old_name='cat_slug',
            new_name='slug',
        ),
    ]
