# Generated by Django 2.2.16 on 2023-08-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, verbose_name='марка автомобиля')),
                ('model', models.CharField(max_length=255, verbose_name='модель автомобиля')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('date', models.DateField(max_length=50, null=True, verbose_name='год выпуска автомобиля')),
                ('price', models.IntegerField(null=True, verbose_name='цена автомобиля')),
                ('number_owners', models.IntegerField(blank=True, null=True, verbose_name='количество владельцев')),
                ('text', models.TextField(blank=True, null=True, verbose_name='описание автомобиля')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='фото автомобиля')),
            ],
        ),
    ]
