# Generated by Django 2.2.16 on 2023-08-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('time_create', 'price'), 'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='category_car',
            options={'verbose_name': 'Категория машин', 'verbose_name_plural': 'Категории машин'},
        ),
        migrations.AlterField(
            model_name='car',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время создания'),
        ),
    ]
