# Generated by Django 2.2.16 on 2023-08-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date',
            field=models.IntegerField(max_length=50, null=True, verbose_name='год выпуска автомобиля'),
        ),
    ]
