# Generated by Django 2.2.16 on 2023-08-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20230828_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='публикация'),
        ),
    ]
