# Generated by Django 2.2.16 on 2023-08-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20230830_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, max_length=255, verbose_name='марка автомобиля'),
        ),
    ]
