# Generated by Django 3.2.20 on 2023-08-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20230811_0636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_model',
            new_name='model',
        ),
    ]
