# Generated by Django 3.2.20 on 2023-08-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='описание автомобиля'),
        ),
        migrations.AlterField(
            model_name='car',
            name='data',
            field=models.DateTimeField(blank=True, max_length=50, null=True, verbose_name='год выпуска автомобиля'),
        ),
    ]
