# Generated by Django 3.2.20 on 2023-08-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20230815_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='data',
            new_name='date',
        ),
    ]
